#%RAML 1.0
title: API with Types
types:
  CustomDate:
    facets:
      onlyFutureDates?:
        type: boolean
      noHolidays:
        type: boolean
    type: date-only
  PossibleMeetingDate:
    type: CustomDate
    noHolidays: true
