#%RAML 1.0
title: simple object
types:
  HasHome:
    type: object
    properties:
      homeAddress: string
  Cat:
    type: object
    properties:
      name: string
      color: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string

  root:
    type: [ HasHome ,  Dog | Cat ]
    properties:
      newProperty: string








